kwejk_mems_homepage:
    path:     /hello/{name}
    defaults: { _controller: KwejkMemsBundle:Default:index }

kwejk_mems_list:
    path:     /{page}
    defaults: { _controller: KwejkMemsBundle:Mems:list, page: 1 }
    requirements: { page: \d+ }

kwejk_mems_show:
    path:     /{slug}
    defaults: { _controller: KwejkMemsBundle:Mems:show }

kwejk_mems_comment_new:
    path:     /comment/new
    defaults: { _controller: KwejkMemsBundle:Comment:new }

kwejk_mems_comment_edit:
    path:     /comment/edit/{id}
    defaults: { _controller: KwejkMemsBundle:Comment:edit }
