kwejk_mems_homepage:
    path:     /hello/{name}
    defaults: { _controller: KwejkMemsBundle:Default:index }

kwejk_mems_list:
    path:     /
    defaults: { _controller: KwejkMemsBundle:Mems:list }

kwejk_mems_show:
    path:     /{slug}
    defaults: { _controller: KwejkMemsBundle:Mems:show }
