parameters:
#    shop_core.example.class: Kwejk\CoreBundle\Example

services:
#    shop_core.example:
#        class: %shop_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
